name: example-environment
channels:
  - conda-forge
  - mcgibbon
dependencies:
  - python = 3.6
  - numpy
  - pandas
  - atmos
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - seaborn
    - matplotlib
    - sphinx>=1.4
    - ipykernel
