name: example-environment
channels:
  - conda-forge
  - mcgibbon
dependencies:
  - python = 3.6
  - numpy
  - scipy
  - sympy
  - matplotlib
  - seaborn
  - pandas
  - ipykernel
  - pip = 9.0.3
  - pip:
    - atmos
